version: '3.9'

networks:
  asgard-net:
    name: asgard-net
    driver: bridge

services:
#  next-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    volumes:
#      - .:/app
#      - node_modules:/app/node_modules
#    environment:
#      - NEXT_PUBLIC_BE_URI=${NEXT_PUBLIC_BE_URI}
#      - SESSION_SECRET=${SESSION_SECRET}
#    networks:
#      - asgard-net
#    depends_on:
#      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - asgard-net
volumes:
#  node_modules:
  db:
    driver: local
